In [25]:
from sklearn.decomposition import PCA
from sklearn import datasets
import numpy as np

In [26]:
iris = datasets.load_iris()

In [27]:
X = iris['data']
y = iris['target']

In [28]:
X_train = X[:100, :]
X_test = X[100:150, :]
y_train = y[:100]
y_test = y[100:150]

In [29]:
pca = PCA()

In [30]:
fit_X_train = pca.fit_transform(X_train)

In [31]:
pca.components_

array([[ 0.32327447, -0.17121498,  0.86913407,  0.33284383],
       [ 0.65835816,  0.74710188, -0.08837738, -0.02434645],
       [-0.67287668,  0.63395111,  0.27341635,  0.26568112],
       [-0.09641117,  0.10310285,  0.40254057, -0.9044533 ]])

In [7]:
fit_X_train.shape

(100, 4)

In [8]:
train_loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
train_loadings

array([[ 0.53822151,  0.31432733, -0.15230047, -0.00986257],
       [-0.28505679,  0.35669724,  0.14348997,  0.01054711],
       [ 1.44702625, -0.042195  ,  0.06188569,  0.04117868],
       [ 0.55415358, -0.011624  ,  0.06013488, -0.09252282]])

In [9]:
fit_X_test = pca.transform(X_test)

In [10]:
test_loadings = pca.components_.T * np.sqrt(pca.explained_variance_)
test_loadings

array([[ 0.53822151,  0.31432733, -0.15230047, -0.00986257],
       [-0.28505679,  0.35669724,  0.14348997,  0.01054711],
       [ 1.44702625, -0.042195  ,  0.06188569,  0.04117868],
       [ 0.55415358, -0.011624  ,  0.06013488, -0.09252282]])

In [13]:
X_train_mean = X_train.mean(axis=0)

In [15]:
X_train_centered = X_train - X_train_mean

In [21]:
weights = np.dot(X_train_centered, pca.components_.T)
weights

array([[-1.65344340e+00,  1.98723344e-01, -5.12987749e-02,
         1.90106555e-02],
       [-1.63249080e+00, -3.06499228e-01, -2.33698994e-01,
        -1.32585356e-02],
       [-1.81830210e+00, -2.79912747e-01,  3.24930209e-04,
        -1.36097877e-02],
       [-1.65968123e+00, -4.38134226e-01,  5.89007568e-02,
         6.62291578e-02],
       [-1.70289234e+00,  2.07597716e-01,  7.93840046e-02,
         3.89620578e-02],
       [-1.29763806e+00,  6.63689042e-01,  1.35579793e-01,
        -2.88000464e-02],
       [-1.76467475e+00, -2.07600569e-01,  2.48312568e-01,
        -3.35393741e-02],
       [-1.58173594e+00,  4.93396025e-02, -2.00645830e-02,
         5.85955443e-02],
       [-1.77700654e+00, -7.10388497e-01,  3.93442364e-02,
         2.46367653e-02],
       [-1.59598327e+00, -2.38192133e-01, -1.69530360e-01,
         1.27751137e-01],
       [-1.50379064e+00,  5.36813431e-01, -9.90299229e-02,
         5.09619308e-02],
       [-1.55947743e+00, -9.11697675e-02,  1.41852388e-01,
      

In [22]:
fit_X_train

array([[-1.65344340e+00,  1.98723344e-01, -5.12987749e-02,
         1.90106555e-02],
       [-1.63249080e+00, -3.06499228e-01, -2.33698994e-01,
        -1.32585356e-02],
       [-1.81830210e+00, -2.79912747e-01,  3.24930209e-04,
        -1.36097877e-02],
       [-1.65968123e+00, -4.38134226e-01,  5.89007568e-02,
         6.62291578e-02],
       [-1.70289234e+00,  2.07597716e-01,  7.93840046e-02,
         3.89620578e-02],
       [-1.29763806e+00,  6.63689042e-01,  1.35579793e-01,
        -2.88000464e-02],
       [-1.76467475e+00, -2.07600569e-01,  2.48312568e-01,
        -3.35393741e-02],
       [-1.58173594e+00,  4.93396025e-02, -2.00645830e-02,
         5.85955443e-02],
       [-1.77700654e+00, -7.10388497e-01,  3.93442364e-02,
         2.46367653e-02],
       [-1.59598327e+00, -2.38192133e-01, -1.69530360e-01,
         1.27751137e-01],
       [-1.50379064e+00,  5.36813431e-01, -9.90299229e-02,
         5.09619308e-02],
       [-1.55947743e+00, -9.11697675e-02,  1.41852388e-01,
      

In [24]:
pca.components_

array([[ 0.32327447, -0.17121498,  0.86913407,  0.33284383],
       [ 0.65835816,  0.74710188, -0.08837738, -0.02434645],
       [-0.67287668,  0.63395111,  0.27341635,  0.26568112],
       [-0.09641117,  0.10310285,  0.40254057, -0.9044533 ]])

In [32]:
pca.mean_

array([5.471, 3.099, 2.861, 0.786])

In [34]:
X_train_mean

array([5.471, 3.099, 2.861, 0.786])